services:
  - type: web
    name: palmistry-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    runtime: python
    autoDeploy: true
    region: oregon
